name: MF_Bluemap
version: ${project.version}
main: com.kilz.mfbluemap.MF_Bluemap
api-version: 1.21
depend: [MedievalFactions, BlueMap]
authors: [Kilz]
description: Integration between MedievalFactions and BlueMap
